/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FarmerEventsWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import static userinterface.Customer.CustomerOrderJPanel.VALID_EMAIL_ADDRESS_REGEX;
import static userinterface.Customer.CustomerOrderJPanel.validate;


/**
 *
 * @author rudrapatel
 */
public class FarmerEventsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerEventsJPanel
     */
    
    private JPanel userProcessContainer;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    FarmerEventsJPanel(JPanel userProcessContainer, UserAccount userAccount, FarmerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        JTableHeader header = tblEvents.getTableHeader();
        TableCellRenderer rendererFromHeader = header.getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        header.setFont(new Font("SansSerif", Font.BOLD, 16));
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
//        valueLabel.setText(userAccount.getEmployee().getName());
        populateEventsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateEventsTable(){
        DefaultTableModel model = (DefaultTableModel)tblEvents.getModel();
        
        model.setRowCount(0);

        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){

            if(request instanceof FarmerEventsWorkRequest){
                Object[] row = new Object[4];
                row[0] = request;
                row[1] = ((FarmerEventsWorkRequest) request).getEventDesc();
                row[2] = ((FarmerEventsWorkRequest) request).getEventDate();
                row[3] = ((FarmerEventsWorkRequest) request).getLocation();
                model.addRow(row);
            }
            
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Description", "Date", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEvents.setRowHeight(25);
        jScrollPane1.setViewportView(tblEvents);
        if (tblEvents.getColumnModel().getColumnCount() > 0) {
            tblEvents.getColumnModel().getColumn(0).setResizable(false);
            tblEvents.getColumnModel().getColumn(1).setResizable(false);
            tblEvents.getColumnModel().getColumn(2).setResizable(false);
            tblEvents.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        jLabel1.setText("Registartion Page For Events");

        jLabel2.setText("Enter Phone Number");

        btnRegister.setBackground(new java.awt.Color(0, 153, 102));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel3.setFont(new java.awt.Font("Bai Jamjuree", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Informational Events");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(504, 504, 504)
                .addComponent(jLabel3)
                .addContainerGap(594, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(btnRegister)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(707, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FarmerWorkAreaJPanel panel = (FarmerWorkAreaJPanel) component;
        panel.populateCheckEventsTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        int rowCount = tblEvents.getRowCount();

if(rowCount==0){
    JOptionPane.showMessageDialog(null, "There is nothing to Register");
    return;
}

int selectedRow = tblEvents.getSelectedRow();
FarmerEventsWorkRequest fNew = new FarmerEventsWorkRequest();

FarmerEventsWorkRequest request = (FarmerEventsWorkRequest)tblEvents.getValueAt(selectedRow, 0);
if (selectedRow < 0){
    JOptionPane.showMessageDialog(null, "Please select a row !");
    return;
}
else
{
    if(txtPhoneNumber.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Phone number cannot be empty");
        return;
    }
    else
    {
        boolean isValidPhoneNumber = validatePhoneNumber(txtPhoneNumber.getText());
        
        if (!isValidPhoneNumber) {
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number (10 digits)");
            return;
        }
        
        List<FarmerEventsWorkRequest> temp = new ArrayList<>();
        for(WorkRequest workRequest :userAccount.getWorkQueue().getWorkRequestList()){
            if(workRequest instanceof FarmerEventsWorkRequest){
                FarmerEventsWorkRequest few = (FarmerEventsWorkRequest) workRequest;
                temp.add(few);                       
            }
        }
        
        
        if(temp.size()==0){
               fNew.setEventDate(request.getEventDate());
               fNew.setEventDesc(request.getEventDesc());
               fNew.setEventName(request.getEventName());
               fNew.setLocation(request.getLocation());
               //fNew.setPhoneNumber(txtPhoneNumber.getText()); // Set phone number
               fNew.setStatus("Registered");
               userAccount.getWorkQueue().getWorkRequestList().add(fNew);
               JOptionPane.showMessageDialog(null, "You have successfully registered for this event");                  
              
        }else{
            boolean flag = true;
            for(FarmerEventsWorkRequest few : temp){
                if(few.getEventName().equalsIgnoreCase(request.getEventName())&&few.getStatus().equalsIgnoreCase("Registered")){
                    JOptionPane.showMessageDialog(null, "Already Registered");   
                    flag=false;
                    } 
            }
            if(flag){
                    fNew.setEventDate(request.getEventDate());
                    fNew.setEventDesc(request.getEventDesc());
                    fNew.setEventName(request.getEventName());
                    fNew.setLocation(request.getLocation());
                    //fNew.setPhoneNumber(txtPhoneNumber.getText()); // Set phone number
                    fNew.setStatus("Registered");
                    userAccount.getWorkQueue().getWorkRequestList().add(fNew);
                    JOptionPane.showMessageDialog(null, "You have successfully registered for this event");
                    
                }
        }
    }

}


    }//GEN-LAST:event_btnRegisterActionPerformed

private boolean validatePhoneNumber(String phoneNumber) {
 
    String cleanedNumber = phoneNumber.replaceAll("[\\s\\-\\(\\)]", "");

    String phoneRegex = "^[0-9]{10}$";
    
    return cleanedNumber.matches(phoneRegex);
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvents;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
