/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Farmer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.FarmerOrganization;
import Business.Organization.OfficerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FarmerSubsidyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.joda.time.LocalDate;
import org.joda.time.Months;

/**
 *
 * @author rudrapatel
 */
public class FarmerViewSubsidyRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private double loss;
    /**
     * Creates new form FarmerViewSubsidyRequestJPanel
     */
    public FarmerViewSubsidyRequestJPanel(JPanel userProcessContainer, UserAccount account, FarmerOrganization organization, Enterprise enterprise, EcoSystem business,double loss) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.loss = loss;
        txtFarmerName.setText(userAccount.getUsername());
        txtLossAmount.setText(String.valueOf(loss));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFarmerName = new javax.swing.JTextField();
        txtLossAmount = new javax.swing.JTextField();
        btnRequestSubsidy = new javax.swing.JButton();
        btnBackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Farmer Name :");

        jLabel2.setText("Losses Amount:");

        txtFarmerName.setEditable(false);
        txtFarmerName.setEnabled(false);

        txtLossAmount.setEditable(false);
        txtLossAmount.setEnabled(false);

        btnRequestSubsidy.setBackground(new java.awt.Color(0, 153, 102));
        btnRequestSubsidy.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestSubsidy.setText("Request Subsidy");
        btnRequestSubsidy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestSubsidyActionPerformed(evt);
            }
        });

        btnBackButton.setText("<< Back");
        btnBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel3.setFont(new java.awt.Font("Bai Jamjuree", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Request Subsidy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(504, 504, 504)
                .addComponent(jLabel3)
                .addContainerGap(594, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(112, 112, 112)
                                .addComponent(txtFarmerName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(102, 102, 102)
                                .addComponent(txtLossAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnRequestSubsidy))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFarmerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLossAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnRequestSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestSubsidyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestSubsidyActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
       

        FarmerSubsidyWorkRequest subsidyWorkRequest = null;

        for(WorkRequest workRequest :userAccount.getWorkQueue().getWorkRequestList()){

            if(workRequest instanceof FarmerSubsidyWorkRequest){
                Date date1 = workRequest.getResolveDate();
                Date date2 = new Date();
                
                
                if(((FarmerSubsidyWorkRequest) workRequest).isIsSubsidyApproved()==false && (Months.monthsBetween(new LocalDate(date2), new LocalDate(date1))).getMonths() < 6){
                    flag=false;
                }else{
                     if((Months.monthsBetween(new LocalDate(date2), new LocalDate(date1))).getMonths() >= 6 ){
                    FarmerSubsidyWorkRequest fs= (FarmerSubsidyWorkRequest) workRequest;
                    subsidyWorkRequest = (FarmerSubsidyWorkRequest) workRequest;
                    if(subsidyWorkRequest.isIsSubsidyApproved()){
                        flag = true;
                        break;
                    }
                }else{

                    JOptionPane.showMessageDialog(null, "Subsidy already given before less than 6 months");
                    flag = true;
                    break;
                }
                }
               

            }
        }
        
        
        if(flag){
            JOptionPane.showMessageDialog(null,"Already issued Subsidy!" );
        }
        else
        {
            FarmerSubsidyWorkRequest farmerSubsidyWorkRequest = new FarmerSubsidyWorkRequest();
            farmerSubsidyWorkRequest.setRequestDate(new Date());
            farmerSubsidyWorkRequest.setSender(userAccount);
            farmerSubsidyWorkRequest.setStatus("Sent");
            farmerSubsidyWorkRequest.setRequestedSubsidyValue(loss);

            Organization org = null;
            for (Network network : business.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof GovernmentEnterprise) {
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof OfficerOrganization) {
                                org = organization;
                                break;
                            }
                        }
                    }

                }
            }

            if (org != null) {
                    org.getWorkQueue().getWorkRequestList().add(farmerSubsidyWorkRequest);
                    userAccount.getWorkQueue().getWorkRequestList().add(farmerSubsidyWorkRequest);
                    // Save to database to persist the subsidy request
                    try {
                        Business.DB4OUtil.DB4OUtil.getInstance().storeSystem(business);
                        JOptionPane.showMessageDialog(null, "You have created request successfully");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Warning: Request created but there was an issue saving to database: " + e.getMessage());
                    }

                
            }
    }//GEN-LAST:event_btnRequestSubsidyActionPerformed
    }
    private void btnBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FarmerWorkAreaJPanel panel = (FarmerWorkAreaJPanel) component;
        panel.populateRequestSubsidyTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackButton;
    private javax.swing.JButton btnRequestSubsidy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFarmerName;
    private javax.swing.JTextField txtLossAmount;
    // End of variables declaration//GEN-END:variables
}
